%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__([<p>__start__</p>]):::first
	research_plan(research_plan)
	asset_sourcing(asset_sourcing)
	scene_coder(scene_coder)
	scene_compiler(scene_compiler)
	__end__([<p>__end__</p>]):::last
	__start__ --> research_plan;
	research_plan --> asset_sourcing;
	scene_coder --> scene_compiler;
	scene_compiler --> __end__;
	asset_sourcing -.-> scene_coder;
	classDef default fill:#f2f0ff,line-height:1.2;
	classDef first fill-opacity:0;
	classDef last fill:#bfb6fc;
